const commonAccountRows = [
  { name: "demo-useradmin@optima.test", detail: "User Admin - active", status: "Active" },
  { name: "demo-manager@optima.test", detail: "Manager - active", status: "Active" },
  { name: "demo-employee-8@optima.test", detail: "Employee - suspended", status: "Suspended" },
];

const commonTaskRows = [
  { name: "Build recommendation dashboard", detail: "Assigned to Ben Carter", status: "Open" },
  { name: "Verify onboarding flow", detail: "Assigned to Farah Noor", status: "Pending" },
  { name: "Prepare support handover", detail: "Assigned to Emma Wong", status: "Open" },
];

export const guestLinks = [
  { label: "Marketing", href: "/guest/marketing" },
  { label: "Features", href: "/guest/features" },
  { label: "Pricing", href: "/guest/pricing" },
  { label: "Feedback", href: "/guest/feedback" },
  { label: "Support", href: "/guest/contact" },
];

export const featureCatalog = {
  passwordRecovery: {
    eyebrow: "4.6 Account Access",
    title: "Password Recovery Page",
    description: "Request a password reset link and track the recovery request for a local demo account.",
    primaryAction: "Send recovery link",
    fields: [
      { name: "email", label: "Account email", type: "email", value: "demo-employee@optima.test" },
      { name: "detail", label: "Recovery note", type: "textarea", value: "Forgot password during demo testing." },
    ],
    rows: [{ name: "demo-employee@optima.test", detail: "Recovery email queued", status: "Pending" }],
    checklist: ["Email capture", "Recovery request record", "Visible success feedback"],
  },
  wrongLogin: {
    eyebrow: "4.3 Authentication",
    title: "Log-in Page with Wrong Details",
    description: "Validates that incorrect credentials are rejected and a clear error is shown without navigating.",
    primaryAction: "Test wrong login",
    fields: [
      { name: "email", label: "Email", type: "email", value: "wrong-user@optima.test" },
      { name: "password", label: "Password", type: "password", value: "wrong-password" },
    ],
    rows: [{ name: "wrong-user@optima.test", detail: "Rejected by demo auth", status: "Suspended" }],
    links: [{ label: "Open real login", href: "/login" }],
    checklist: ["Wrong email validation", "Wrong password validation", "No dashboard redirect on failure"],
  },
  guestMarketing: {
    eyebrow: "4.7.1 Guest",
    title: "Marketing Website Page",
    description: "Public Optima overview for guest users with value proposition, navigation, and conversion actions.",
    primaryAction: "Capture lead",
    fields: [
      { name: "name", label: "Visitor name", value: "Prospective Team Lead" },
      { name: "email", label: "Business email", type: "email", value: "lead@company.test" },
      { name: "detail", label: "Interest", type: "textarea", value: "Interested in smart task allocation." },
    ],
    metrics: [
      { label: "Demo leads", value: "24" },
      { label: "Conversion", value: "18%" },
      { label: "Feature clicks", value: "143" },
    ],
    links: guestLinks,
    rows: [
      { name: "Smart allocation", detail: "Promoted as the core value proposition", status: "Active" },
      { name: "Team visibility", detail: "Supports managers and employees", status: "Active" },
    ],
    checklist: ["Hero message", "Guest navigation", "Lead capture", "Call to sign up"],
  },
  guestFeatures: {
    eyebrow: "4.7.2 Guest",
    title: "Basic Features Page",
    description: "Explains free/basic features available before subscription upgrade.",
    primaryAction: "Save feature interest",
    fields: [
      { name: "name", label: "Feature", value: "Task board" },
      { name: "detail", label: "Use case", value: "Create and update assigned tasks" },
      { name: "status", label: "Interest", type: "select", options: ["Open", "Pending", "Active"], value: "Active" },
    ],
    links: guestLinks,
    rows: [
      { name: "Task management", detail: "Create, update, delete tasks", status: "Active" },
      { name: "Employee search", detail: "Find available employees", status: "Active" },
      { name: "Feedback submission", detail: "Send feedback to platform admins", status: "Open" },
    ],
    checklist: ["Basic feature list", "Searchable records", "Feature interest capture"],
  },
  guestPricing: {
    eyebrow: "4.7.3 Guest",
    title: "Paid Features / Subscription Plans Page",
    description: "Compares Starter, Team, and Enterprise subscription plans for public visitors.",
    primaryAction: "Select plan",
    fields: [
      { name: "name", label: "Plan", type: "select", options: ["Starter", "Team", "Enterprise"], value: "Team" },
      { name: "detail", label: "Billing contact", type: "email", value: "billing@company.test" },
      { name: "status", label: "Plan status", type: "select", options: ["Pending", "Active"], value: "Pending" },
    ],
    metrics: [
      { label: "Starter", value: "$0" },
      { label: "Team", value: "$19" },
      { label: "Enterprise", value: "Custom" },
    ],
    links: guestLinks,
    rows: [
      { name: "Starter", detail: "Basic task board and profile pages", status: "Active" },
      { name: "Team", detail: "Automated assignment and team analytics", status: "Active" },
      { name: "Enterprise", detail: "Audit logs, priority support, SSO readiness", status: "Pending" },
    ],
    checklist: ["Plan comparison", "Upgrade request", "Subscription status tracking"],
  },
  guestFeedback: {
    eyebrow: "4.7.4 Guest",
    title: "User Feedback Page",
    description: "Public feedback form for guests to submit comments before creating an account.",
    primaryAction: "Submit feedback",
    fields: [
      { name: "name", label: "Feedback title", value: "Need mobile task view" },
      { name: "detail", label: "Feedback", type: "textarea", value: "A mobile-friendly task board would help field employees." },
      { name: "status", label: "Feedback status", type: "select", options: ["Open", "Pending", "Completed"], value: "Open" },
    ],
    links: guestLinks,
    rows: [
      { name: "Need mobile task view", detail: "Guest feature request", status: "Open" },
      { name: "Pricing clarity", detail: "Asked for Enterprise examples", status: "Pending" },
    ],
    checklist: ["Feedback form", "Feedback list", "Status update"],
  },
  guestContact: {
    eyebrow: "4.7.5 Guest",
    title: "Contact Support Page",
    description: "Allows guests to submit contact inquiries and support requests.",
    primaryAction: "Send inquiry",
    fields: [
      { name: "name", label: "Subject", value: "Implementation question" },
      { name: "email", label: "Reply email", type: "email", value: "guest@company.test" },
      { name: "detail", label: "Inquiry", type: "textarea", value: "How long does onboarding take for a 30-person team?" },
    ],
    links: guestLinks,
    rows: [
      { name: "Implementation question", detail: "Guest contact inquiry", status: "Open" },
      { name: "Pricing contact", detail: "Sent to sales queue", status: "Pending" },
    ],
    checklist: ["Contact form", "Inquiry queue", "Support status tracking"],
  },
  userAdminDashboard: {
    eyebrow: "4.8 User Admin",
    title: "User Admin Dashboard",
    description: "Central workspace for managing accounts, roles, organization profile, and platform support.",
    links: [
      { label: "Accounts", href: "/useradmin/accounts" },
      { label: "Create Account", href: "/useradmin/accounts/create" },
      { label: "Password Resets", href: "/useradmin/password-resets" },
      { label: "Roles", href: "/useradmin/roles" },
      { label: "Support", href: "/useradmin/support" },
    ],
    metrics: [
      { label: "Accounts", value: "14" },
      { label: "Employees", value: "11" },
      { label: "Roles", value: "4" },
      { label: "Suspended", value: "1" },
    ],
    fields: [
      { name: "name", label: "Admin note", value: "Review pending employee account" },
      { name: "detail", label: "Action", value: "Check account status and assigned role" },
    ],
    rows: commonAccountRows,
    checklist: ["Account overview", "Password reset queue", "Role shortcuts", "Organization shortcut", "Support shortcut"],
  },
  createUserAccount: {
    eyebrow: "4.8.2 User Admin",
    title: "Create User Account Page",
    description: "Create a user account with email, username, role, organization, and initial status.",
    primaryAction: "Create account",
    fields: [
      { name: "name", label: "Username", value: "New Demo Employee" },
      { name: "email", label: "Email", type: "email", value: "new.employee@optima.test" },
      { name: "role", label: "Role", type: "select", options: ["User Admin", "Manager", "Employee"], value: "Employee" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Pending", "Suspended"], value: "Pending" },
    ],
    rows: commonAccountRows,
    checklist: ["Capture email", "Assign role", "Set account status", "Add to account list"],
  },
  updateUserAccount: {
    eyebrow: "4.8.3 User Admin",
    title: "Update User Account Page",
    description: "Update account profile details, email, role, organization, and status.",
    primaryAction: "Update account",
    fields: [
      { name: "name", label: "Account", value: "Ben Carter" },
      { name: "email", label: "Email", type: "email", value: "demo-employee@optima.test" },
      { name: "role", label: "Role", type: "select", options: ["Manager", "Employee", "User Admin"], value: "Employee" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Pending", "Suspended"], value: "Active" },
    ],
    rows: commonAccountRows,
    checklist: ["Editable profile", "Role update", "Organization update", "Status update"],
  },
  statusUserAccount: {
    eyebrow: "4.8.4 User Admin",
    title: "Delete / Suspend User Account Page",
    description: "Suspend, reactivate, or remove user accounts from the local demo account queue.",
    primaryAction: "Apply status action",
    fields: [
      { name: "name", label: "Account", value: "demo-employee-8@optima.test" },
      { name: "status", label: "Action", type: "select", options: ["Suspended", "Active"], value: "Suspended" },
      { name: "detail", label: "Reason", value: "Temporary access hold" },
    ],
    rows: commonAccountRows,
    checklist: ["Suspend account", "Reactivate account", "Delete local record", "Status audit"],
  },
  assignRoles: {
    eyebrow: "4.8.5 User Admin",
    title: "Assign Roles Page",
    description: "Assign platform roles to existing accounts and validate destination dashboard access.",
    primaryAction: "Assign role",
    fields: [
      { name: "name", label: "Account", value: "demo-employee-2@optima.test" },
      { name: "role", label: "New role", type: "select", options: ["User Admin", "Manager", "Employee"], value: "Employee" },
      { name: "detail", label: "Reason", value: "Project staffing update" },
    ],
    rows: [
      { name: "User Admin", detail: "Routes to /useradmin/accounts", status: "Active" },
      { name: "Manager", detail: "Routes to /manager/workspace", status: "Active" },
      { name: "Employee", detail: "Routes to /employee/workspace", status: "Active" },
    ],
    checklist: ["Select user", "Choose role", "Show route impact", "Save assignment"],
  },
  rolePermissions: {
    eyebrow: "4.8.6 User Admin",
    title: "Role Permissions Page",
    description: "Review permissions granted to Platform Admin, User Admin, Manager, and Employee roles.",
    primaryAction: "Save permission set",
    fields: [
      { name: "name", label: "Permission", value: "Manage accounts" },
      { name: "role", label: "Role", type: "select", options: ["Platform Admin", "User Admin", "Manager", "Employee"], value: "User Admin" },
      { name: "status", label: "Permission status", type: "select", options: ["Active", "Pending"], value: "Active" },
    ],
    rows: [
      { name: "Manage accounts", detail: "User Admin", status: "Active" },
      { name: "Manage subscriptions", detail: "Platform Admin", status: "Active" },
      { name: "Assign tasks", detail: "Manager", status: "Active" },
      { name: "Request task assignment", detail: "Employee", status: "Active" },
    ],
    checklist: ["Permission matrix", "Role mapping", "Status update", "Search permissions"],
  },
  userAdminProfile: {
    eyebrow: "4.8.8 User Admin",
    title: "User Admin Profile Page",
    description: "Edit local User Admin profile details and contact preferences.",
    primaryAction: "Save profile",
    fields: [
      { name: "name", label: "Full name", value: "User Admin Lead" },
      { name: "email", label: "Email", type: "email", value: "demo-useradmin@optima.test" },
      { name: "detail", label: "Bio", type: "textarea", value: "Responsible for account and organization setup." },
    ],
    rows: [{ name: "User Admin Lead", detail: "Account administration profile", status: "Active" }],
    checklist: ["Profile edit", "Contact email", "Local save feedback"],
  },
  userAdminSupport: {
    eyebrow: "4.8.9 User Admin",
    title: "Contact Platform Support Page",
    description: "Submit account, role, or organization support cases to platform admins.",
    primaryAction: "Submit support case",
    fields: [
      { name: "name", label: "Case title", value: "Need role permission review" },
      { name: "detail", label: "Case details", type: "textarea", value: "Please confirm Manager can access automated assignment." },
      { name: "status", label: "Priority", type: "select", options: ["Open", "Pending"], value: "Open" },
    ],
    rows: [{ name: "Need role permission review", detail: "Platform support queue", status: "Open" }],
    checklist: ["Support form", "Case tracking", "Priority status"],
  },
  platformDashboard: {
    eyebrow: "4.9 Platform Admin",
    title: "Platform Admin Dashboard",
    description: "Control center for system activity, homepage content, plans, feedback, and inquiries.",
    links: [
      { label: "Activity Logs", href: "/platformadmin/activity-logs" },
      { label: "Plans", href: "/platformadmin/subscriptions" },
      { label: "Feedback", href: "/platformadmin/feedback" },
      { label: "Inquiries", href: "/platformadmin/inquiries" },
    ],
    metrics: [
      { label: "Active orgs", value: "8" },
      { label: "Open feedback", value: "12" },
      { label: "Plan changes", value: "3" },
      { label: "Inquiries", value: "6" },
    ],
    fields: [
      { name: "name", label: "Admin action", value: "Review latest system activity" },
      { name: "detail", label: "Notes", value: "Check activity, subscriptions, and feedback queues." },
    ],
    rows: [
      { name: "Login audit", detail: "14 demo accounts available", status: "Active" },
      { name: "Plan review", detail: "Enterprise inquiry pending", status: "Pending" },
    ],
    checklist: ["System overview", "Management shortcuts", "Queue records"],
  },
  activityLogs: {
    eyebrow: "4.9.1 Platform Admin",
    title: "System Activity Logs Page",
    description: "Review login, account, task, and subscription events across the platform.",
    primaryAction: "Add audit note",
    fields: [
      { name: "name", label: "Event", value: "Manager logged in" },
      { name: "detail", label: "Details", value: "demo-manager@optima.test accessed workspace" },
      { name: "status", label: "Severity", type: "select", options: ["Active", "Pending"], value: "Active" },
    ],
    rows: [
      { name: "Manager logged in", detail: "Workspace access", status: "Active" },
      { name: "User Admin listed accounts", detail: "14 accounts returned", status: "Active" },
    ],
    checklist: ["Audit log list", "Search logs", "Add log note", "Severity status"],
  },
  homepageManagement: {
    eyebrow: "4.9.2 Platform Admin",
    title: "Homepage Management Page",
    description: "Manage landing page hero copy, feature highlights, and public calls to action.",
    primaryAction: "Publish homepage update",
    fields: [
      { name: "name", label: "Headline", value: "Every Great Team Runs on Optima" },
      { name: "detail", label: "Supporting copy", type: "textarea", value: "One intelligent workspace for everything your team needs." },
      { name: "status", label: "Publish status", type: "select", options: ["Pending", "Active"], value: "Pending" },
    ],
    rows: [
      { name: "Hero section", detail: "Landing page headline", status: "Active" },
      { name: "Pricing CTA", detail: "Links to subscription plans", status: "Pending" },
    ],
    checklist: ["Hero copy edit", "CTA status", "Homepage records"],
  },
  subscriptionManagement: {
    eyebrow: "4.9.3 Platform Admin",
    title: "Subscription Plan Management Page",
    description: "Create and update Starter, Team, and Enterprise plan offerings.",
    primaryAction: "Save plan",
    fields: [
      { name: "name", label: "Plan name", type: "select", options: ["Starter", "Team", "Enterprise"], value: "Team" },
      { name: "detail", label: "Plan features", value: "Automated assignment, team dashboards, feedback analytics" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Pending"], value: "Active" },
    ],
    rows: [
      { name: "Starter", detail: "Basic workspace", status: "Active" },
      { name: "Team", detail: "Automation and dashboards", status: "Active" },
      { name: "Enterprise", detail: "Priority support and advanced governance", status: "Pending" },
    ],
    checklist: ["Plan create", "Plan update", "Status toggle", "Feature list"],
  },
  feedbackManagement: {
    eyebrow: "4.9.4 Platform Admin",
    title: "User Feedback Management Page",
    description: "Triage user feedback from guests, managers, and employees.",
    primaryAction: "Add response",
    fields: [
      { name: "name", label: "Feedback", value: "Need mobile task view" },
      { name: "detail", label: "Response", type: "textarea", value: "Moved to product review queue." },
      { name: "status", label: "Status", type: "select", options: ["Open", "Pending", "Completed"], value: "Pending" },
    ],
    rows: [
      { name: "Need mobile task view", detail: "Guest", status: "Open" },
      { name: "Better assignment explanation", detail: "Manager", status: "Pending" },
      { name: "Clock-out reminder", detail: "Employee", status: "Open" },
    ],
    checklist: ["Feedback list", "Status update", "Admin response", "Search feedback"],
  },
  feedbackAnalysis: {
    eyebrow: "4.9.5 Platform Admin",
    title: "Feedback Analysis Page",
    description: "Summarize feedback trends by role, sentiment, and feature category.",
    primaryAction: "Save analysis",
    fields: [
      { name: "name", label: "Insight", value: "Task automation is the top manager request" },
      { name: "detail", label: "Evidence", type: "textarea", value: "5 of 12 open feedback items mention assignment recommendations." },
      { name: "status", label: "Confidence", type: "select", options: ["Pending", "Active"], value: "Active" },
    ],
    metrics: [
      { label: "Positive", value: "68%" },
      { label: "Neutral", value: "21%" },
      { label: "Negative", value: "11%" },
    ],
    rows: [
      { name: "Automation requests", detail: "Manager feedback theme", status: "Active" },
      { name: "Mobile usability", detail: "Guest and employee theme", status: "Pending" },
    ],
    checklist: ["Feedback grouping", "Trend metrics", "Insight capture"],
  },
  inquiryManagement: {
    eyebrow: "4.9.6 Platform Admin",
    title: "Contact Inquiry Management Page",
    description: "Manage support and sales inquiries submitted by guests and application users.",
    primaryAction: "Assign inquiry",
    fields: [
      { name: "name", label: "Inquiry", value: "Enterprise pricing request" },
      { name: "detail", label: "Assignee", value: "Platform Admin" },
      { name: "status", label: "Status", type: "select", options: ["Open", "Pending", "Completed"], value: "Open" },
    ],
    rows: [
      { name: "Enterprise pricing request", detail: "Guest inquiry", status: "Open" },
      { name: "Account access issue", detail: "User Admin support", status: "Pending" },
    ],
    checklist: ["Inquiry queue", "Assign owner", "Update status", "Delete resolved record"],
  },
  platformProfile: {
    eyebrow: "4.9.7 Platform Admin",
    title: "Platform Admin Profile Page",
    description: "Maintain the platform admin profile and operational contact details.",
    primaryAction: "Save profile",
    fields: [
      { name: "name", label: "Name", value: "Platform Owner" },
      { name: "email", label: "Email", type: "email", value: "demo-platform@optima.test" },
      { name: "detail", label: "Responsibility", value: "Platform operations and subscription governance" },
    ],
    rows: [{ name: "Platform Owner", detail: "Primary platform administrator", status: "Active" }],
    checklist: ["Profile edit", "Contact update", "Operational role record"],
  },
  managerCreateTask: {
    eyebrow: "4.10.2 Manager",
    title: "Create Task Page",
    description: "Create a task with title, description, priority, status, assignee, and due date.",
    primaryAction: "Create task",
    fields: [
      { name: "title", label: "Task title", value: "Review allocation score" },
      { name: "description", label: "Description", type: "textarea", value: "Check suggested employees before assignment." },
      { name: "status", label: "Status", type: "select", options: ["Open", "Pending", "Completed"], value: "Open" },
      { name: "detail", label: "Assigned to", value: "Ben Carter" },
    ],
    rows: commonTaskRows,
    checklist: ["Task form", "Priority/status capture", "Assignee field", "Task list update"],
  },
  managerUpdateTask: {
    eyebrow: "4.10.3 Manager",
    title: "Update Task Page",
    description: "Modify task details, assignment, priority, status, and timeline.",
    primaryAction: "Update task",
    fields: [
      { name: "title", label: "Task title", value: "Build recommendation dashboard" },
      { name: "detail", label: "Assigned to", value: "Chloe Lim" },
      { name: "status", label: "Status", type: "select", options: ["Open", "Pending", "Completed"], value: "Pending" },
    ],
    rows: commonTaskRows,
    checklist: ["Edit task", "Change assignee", "Change status", "Save update"],
  },
  managerDeleteTask: {
    eyebrow: "4.10.4 Manager",
    title: "Delete Task Page",
    description: "Remove obsolete tasks and keep a visible deletion record in the local queue.",
    primaryAction: "Mark for deletion",
    fields: [
      { name: "title", label: "Task", value: "Prepare support handover" },
      { name: "detail", label: "Reason", value: "Merged into another support task" },
      { name: "status", label: "Status", type: "select", options: ["Pending", "Completed"], value: "Pending" },
    ],
    rows: commonTaskRows,
    checklist: ["Select task", "Confirm deletion reason", "Remove from records"],
  },
  managerEmployees: {
    eyebrow: "4.10.5 Manager",
    title: "Employee List Page",
    description: "View employees with role, availability, skills, and assignment readiness.",
    primaryAction: "Add employee note",
    fields: [
      { name: "name", label: "Employee", value: "Ben Carter" },
      { name: "detail", label: "Manager note", value: "Strong match for frontend tasks" },
      { name: "status", label: "Availability", type: "select", options: ["Active", "Pending", "Suspended"], value: "Active" },
    ],
    rows: [
      { name: "Ben Carter", detail: "Frontend, Backend - Available", status: "Active" },
      { name: "Chloe Lim", detail: "Backend, Automation - Available", status: "Active" },
      { name: "Emma Wong", detail: "Support, Documentation - Busy", status: "Pending" },
    ],
    checklist: ["Employee cards", "Availability view", "Skills view", "Manager notes"],
  },
  managerSearchEmployees: {
    eyebrow: "4.10.6 Manager",
    title: "Search Employee Page",
    description: "Search employees by name, email, department, skills, or availability status.",
    primaryAction: "Save search",
    fields: [
      { name: "name", label: "Search name", value: "Available frontend employee" },
      { name: "detail", label: "Criteria", value: "Frontend skill and active availability" },
    ],
    rows: [
      { name: "Ben Carter", detail: "Frontend, available", status: "Active" },
      { name: "George Lee", detail: "Frontend, automation", status: "Active" },
      { name: "Emma Wong", detail: "Support, busy", status: "Pending" },
    ],
    checklist: ["Search box", "Filtered records", "Skill criteria", "Availability criteria"],
  },
  manualAssignment: {
    eyebrow: "4.10.7 Manager",
    title: "Manual Task Assignment Page",
    description: "Manually assign a task to an employee after reviewing workload and skills.",
    primaryAction: "Assign manually",
    fields: [
      { name: "title", label: "Task", value: "Build recommendation dashboard" },
      { name: "detail", label: "Employee", value: "Ben Carter" },
      { name: "status", label: "Assignment status", type: "select", options: ["Pending", "Active", "Completed"], value: "Active" },
    ],
    rows: commonTaskRows,
    checklist: ["Task selection", "Employee selection", "Manual assignment", "Assignment status"],
  },
  autoAssignment: {
    eyebrow: "4.10.8 Manager",
    title: "Automated Task Assignment Page",
    description: "Run an automated assignment scan using skills, availability, workload, and task priority.",
    primaryAction: "Run auto assignment",
    fields: [
      { name: "title", label: "Task", value: "Build recommendation dashboard" },
      { name: "detail", label: "Recommendation", value: "Ben Carter - best match" },
      { name: "status", label: "Decision", type: "select", options: ["Pending", "Active", "Completed"], value: "Pending" },
    ],
    metrics: [
      { label: "Best match", value: "Ben" },
      { label: "Score", value: "94" },
      { label: "Eligible", value: "8" },
    ],
    rows: [
      { name: "Ben Carter", detail: "Score 94 - Frontend + available", status: "Active" },
      { name: "George Lee", detail: "Score 88 - Frontend + automation", status: "Pending" },
    ],
    checklist: ["Eligibility scan", "Recommendation score", "Confirm assignment", "Fallback candidate"],
  },
  eligibilityEvaluation: {
    eyebrow: "4.10.9 Manager",
    title: "Employee Eligibility Evaluation Page",
    description: "Evaluate employee fit based on skills, workload, availability, status, and schedule.",
    primaryAction: "Save evaluation",
    fields: [
      { name: "name", label: "Employee", value: "Ben Carter" },
      { name: "detail", label: "Evaluation", value: "Eligible for high priority frontend work" },
      { name: "status", label: "Eligibility", type: "select", options: ["Active", "Pending", "Suspended"], value: "Active" },
    ],
    rows: [
      { name: "Ben Carter", detail: "Eligible - score 94", status: "Active" },
      { name: "Emma Wong", detail: "Busy - support focus", status: "Pending" },
      { name: "Ivan Patel", detail: "Suspended account", status: "Suspended" },
    ],
    checklist: ["Skills check", "Availability check", "Status check", "Eligibility result"],
  },
  requestReview: {
    eyebrow: "4.10.10 Manager",
    title: "Task Assignment Request Review Page",
    description: "Review employee requests to claim available tasks and approve or reject them.",
    primaryAction: "Record decision",
    fields: [
      { name: "name", label: "Request", value: "Ben Carter requests task 101" },
      { name: "detail", label: "Decision note", value: "Approved based on skill match" },
      { name: "status", label: "Decision", type: "select", options: ["Pending", "Active", "Completed"], value: "Active" },
    ],
    rows: [
      { name: "Ben Carter -> task 101", detail: "Frontend skill match", status: "Pending" },
      { name: "Farah Noor -> task 102", detail: "QA flow request", status: "Active" },
    ],
    checklist: ["Request queue", "Approve action", "Reject/delete action", "Decision notes"],
  },
  allocationHistory: {
    eyebrow: "4.10.11 Manager",
    title: "Task Allocation History Page",
    description: "Review manual and automated task allocation history for audit and reporting.",
    primaryAction: "Add history note",
    fields: [
      { name: "name", label: "History item", value: "Task 101 assigned to Ben Carter" },
      { name: "detail", label: "Reason", value: "Automated score 94" },
      { name: "status", label: "Outcome", type: "select", options: ["Active", "Completed"], value: "Completed" },
    ],
    rows: [
      { name: "Task 101 -> Ben Carter", detail: "Automated recommendation accepted", status: "Completed" },
      { name: "Task 102 -> Farah Noor", detail: "Manual assignment", status: "Completed" },
    ],
    checklist: ["History table", "Assignment reason", "Manual/auto source", "Audit status"],
  },
  managerFeedback: {
    eyebrow: "4.10.12 Manager",
    title: "Submit Feedback Page",
    description: "Submit manager feedback about task allocation, team workload, or workspace issues.",
    primaryAction: "Submit feedback",
    fields: [
      { name: "name", label: "Feedback title", value: "Explain recommendation score" },
      { name: "detail", label: "Feedback", type: "textarea", value: "Managers need a clear reason for automated assignment suggestions." },
      { name: "status", label: "Status", type: "select", options: ["Open", "Pending"], value: "Open" },
    ],
    rows: [{ name: "Explain recommendation score", detail: "Manager feedback", status: "Open" }],
    checklist: ["Feedback form", "Manager context", "Status tracking"],
  },
  managerProfile: {
    eyebrow: "4.10.13 Manager",
    title: "Manager Profile Page",
    description: "Update manager profile, department, contact information, and notification preference.",
    primaryAction: "Save profile",
    fields: [
      { name: "name", label: "Full name", value: "Alicia Tan" },
      { name: "email", label: "Email", type: "email", value: "demo-manager@optima.test" },
      { name: "detail", label: "Role summary", value: "Delivery Manager for Workflow Excellence" },
    ],
    rows: [{ name: "Alicia Tan", detail: "Delivery Manager", status: "Active" }],
    checklist: ["Profile edit", "Contact update", "Department summary"],
  },
  employeeAssignedTasks: {
    eyebrow: "4.11.1 Employee",
    title: "Assigned Tasks Page",
    description: "View assigned tasks, priorities, due dates, status, comments, and files.",
    primaryAction: "Add task note",
    fields: [
      { name: "title", label: "Task", value: "Build recommendation dashboard" },
      { name: "detail", label: "Progress note", value: "Working on frontend chart state" },
      { name: "status", label: "Status", type: "select", options: ["Open", "Pending", "Completed"], value: "Open" },
    ],
    rows: commonTaskRows,
    checklist: ["Assigned task list", "Priority view", "Due date view", "Task note"],
  },
  employeeAvailableTasks: {
    eyebrow: "4.11.2 Employee",
    title: "Available Tasks Page",
    description: "Browse open tasks that employees can request based on eligibility.",
    primaryAction: "Request task",
    fields: [
      { name: "title", label: "Available task", value: "Prepare support handover" },
      { name: "detail", label: "Reason", value: "I have documentation and support experience" },
      { name: "status", label: "Request status", type: "select", options: ["Pending", "Active"], value: "Pending" },
    ],
    rows: [
      { name: "Prepare support handover", detail: "Support + documentation", status: "Open" },
      { name: "Verify onboarding flow", detail: "QA skill preferred", status: "Open" },
    ],
    checklist: ["Available tasks", "Eligibility hint", "Create request"],
  },
  employeeTaskStatus: {
    eyebrow: "4.11.3 Employee",
    title: "Update Task Status Page",
    description: "Update assigned task status from Open to In Progress, Completed, or Cancelled.",
    primaryAction: "Update status",
    fields: [
      { name: "title", label: "Task", value: "Build recommendation dashboard" },
      { name: "status", label: "New status", type: "select", options: ["Open", "Pending", "Completed"], value: "Pending" },
      { name: "detail", label: "Update note", value: "Moved into implementation." },
    ],
    rows: commonTaskRows,
    checklist: ["Select task", "Change status", "Progress note", "Status history"],
  },
  employeeCreateRequest: {
    eyebrow: "4.11.4 Employee",
    title: "Create Task Assignment Request Page",
    description: "Submit a request to be assigned to an available task.",
    primaryAction: "Create request",
    fields: [
      { name: "title", label: "Task", value: "Prepare support handover" },
      { name: "detail", label: "Request reason", type: "textarea", value: "I can take this because I have support and documentation skills." },
      { name: "status", label: "Request status", type: "select", options: ["Pending", "Active"], value: "Pending" },
    ],
    rows: [
      { name: "Prepare support handover", detail: "Pending manager review", status: "Pending" },
      { name: "Verify onboarding flow", detail: "Approved previously", status: "Active" },
    ],
    checklist: ["Task selection", "Reason capture", "Submit request", "Pending state"],
  },
  employeeMyRequests: {
    eyebrow: "4.11.5 Employee",
    title: "My Task Assignment Requests Page",
    description: "View all submitted task assignment requests and their review status.",
    primaryAction: "Add request note",
    fields: [
      { name: "name", label: "Request", value: "Task 103 assignment request" },
      { name: "detail", label: "Note", value: "Waiting for manager decision" },
      { name: "status", label: "Status", type: "select", options: ["Pending", "Active", "Completed"], value: "Pending" },
    ],
    rows: [
      { name: "Task 103 assignment request", detail: "Pending review", status: "Pending" },
      { name: "Task 102 assignment request", detail: "Approved", status: "Active" },
    ],
    checklist: ["Request list", "Review status", "Search requests"],
  },
  employeeCancelRequest: {
    eyebrow: "4.11.6 Employee",
    title: "Cancel Task Assignment Request Page",
    description: "Cancel pending task assignment requests and record a cancellation reason.",
    primaryAction: "Cancel request",
    fields: [
      { name: "name", label: "Request", value: "Task 103 assignment request" },
      { name: "detail", label: "Cancel reason", value: "Schedule changed" },
      { name: "status", label: "Result", type: "select", options: ["Pending", "Completed"], value: "Completed" },
    ],
    rows: [
      { name: "Task 103 assignment request", detail: "Pending review", status: "Pending" },
      { name: "Cancelled support request", detail: "Schedule changed", status: "Completed" },
    ],
    checklist: ["Select pending request", "Reason capture", "Cancel action"],
  },
  employeeClockIn: {
    eyebrow: "4.11.7 Employee",
    title: "Clock In Page",
    description: "Clock in for the work day and update employee availability for assignment decisions.",
    primaryAction: "Clock in",
    fields: [
      { name: "name", label: "Employee", value: "Ben Carter" },
      { name: "detail", label: "Location", value: "Remote" },
      { name: "status", label: "Availability", type: "select", options: ["Active", "Pending"], value: "Active" },
    ],
    rows: [
      { name: "Ben Carter", detail: "Clocked in at 09:00", status: "Active" },
      { name: "Chloe Lim", detail: "Clocked in at 09:15", status: "Active" },
    ],
    checklist: ["Clock in action", "Availability update", "Time record"],
  },
  employeeClockOut: {
    eyebrow: "4.11.8 Employee",
    title: "Clock Out Page",
    description: "Clock out and close the active availability window for the current day.",
    primaryAction: "Clock out",
    fields: [
      { name: "name", label: "Employee", value: "Ben Carter" },
      { name: "detail", label: "End note", value: "Completed assigned dashboard work" },
      { name: "status", label: "Availability", type: "select", options: ["Completed", "Pending"], value: "Completed" },
    ],
    rows: [
      { name: "Ben Carter", detail: "Clock-out pending", status: "Pending" },
      { name: "Farah Noor", detail: "Clocked out at 17:30", status: "Completed" },
    ],
    checklist: ["Clock out action", "End note", "Availability close"],
  },
  employeeFeedback: {
    eyebrow: "4.11.9 Employee",
    title: "Submit Feedback Page",
    description: "Submit employee feedback about assigned tasks, requests, workload, or clock-in flow.",
    primaryAction: "Submit feedback",
    fields: [
      { name: "name", label: "Feedback title", value: "Need clearer request status" },
      { name: "detail", label: "Feedback", type: "textarea", value: "Employees need notifications when managers approve or reject requests." },
      { name: "status", label: "Status", type: "select", options: ["Open", "Pending"], value: "Open" },
    ],
    rows: [{ name: "Need clearer request status", detail: "Employee feedback", status: "Open" }],
    checklist: ["Feedback form", "Employee source", "Status tracking"],
  },
  employeeProfile: {
    eyebrow: "4.11.10 Employee",
    title: "Employee Profile Page",
    description: "Maintain employee profile, skills, department, availability, and contact details.",
    primaryAction: "Save profile",
    fields: [
      { name: "name", label: "Full name", value: "Ben Carter" },
      { name: "email", label: "Email", type: "email", value: "demo-employee@optima.test" },
      { name: "detail", label: "Skills", value: "Frontend, Backend" },
    ],
    rows: [{ name: "Ben Carter", detail: "Frontend, Backend - Available", status: "Active" }],
    checklist: ["Profile edit", "Skill list", "Availability summary", "Contact update"],
  },
};
