export const sideMenuNavigation = {
  useradmin: {
    label: "User Admin",
    homeHref: "/useradmin/accounts",
    items: [
      { label: "Dashboard", href: "/useradmin", icon: "home" },
      { label: "Accounts", href: "/useradmin/accounts", icon: "users" },
      { label: "Create Account", href: "/useradmin/accounts/create", icon: "users" },
      { label: "Password Resets", href: "/useradmin/password-resets", icon: "inbox" },
      { label: "Organization", href: "/useradmin/organization", icon: "organization" },
      { label: "Roles", href: "/useradmin/roles", icon: "settings" },
      { label: "Permissions", href: "/useradmin/roles/permissions", icon: "settings" },
      { label: "My Space", href: "/useradmin/my-space", icon: "home" },
      { label: "Profile", href: "/useradmin/profile", icon: "home" },
      { label: "Support", href: "/useradmin/support", icon: "support" },
    ],
  },
  platformadmin: {
    label: "Platform Admin",
    homeHref: "/platformadmin",
    items: [
      { label: "Dashboard", href: "/platformadmin", icon: "home" },
      { label: "Activity Logs", href: "/platformadmin/activity-logs", icon: "archive" },
      { label: "Homepage", href: "/platformadmin/homepage", icon: "workspace" },
      { label: "Plans", href: "/platformadmin/subscriptions", icon: "settings" },
      { label: "Feedback", href: "/platformadmin/feedback", icon: "inbox" },
      { label: "Avatar Reviews", href: "/platformadmin/avatar-reviews", icon: "users" },
      { label: "Analysis", href: "/platformadmin/feedback-analysis", icon: "tasks" },
      { label: "Inquiries", href: "/platformadmin/inquiries", icon: "support" },
      { label: "My Space", href: "/platformadmin/my-space", icon: "home" },
      { label: "Profile", href: "/platformadmin/profile", icon: "home" },
    ],
  },
  manager: {
    label: "Manager",
    homeHref: "/manager/workspace",
    items: [
      { label: "Workspace", href: "/manager/workspace", icon: "workspace" },
      { label: "Tasks", href: "/manager/tasks", icon: "tasks" },
      { label: "Employees", href: "/manager/employees", icon: "users" },
      { label: "Auto Assign", href: "/manager/auto-assignment", icon: "tasks" },
      { label: "Requests", href: "/manager/requests", icon: "inbox" },
      { label: "History", href: "/manager/history", icon: "archive" },
      { label: "Team", href: "/manager/team", icon: "users" },
      { label: "Organization", href: "/manager/organization", icon: "organization" },
      { label: "Inbox", href: "/manager/inbox", icon: "inbox" },
      { label: "My Space", href: "/manager/my-space", icon: "home" },
      { label: "Archive", href: "/manager/archive", icon: "archive" },
      { label: "Profile", href: "/manager/profile", icon: "home" },
      { label: "Support", href: "/manager/support", icon: "support" },
    ],
  },
  employee: {
    label: "Employee",
    homeHref: "/employee/workspace",
    items: [
      { label: "Workspace", href: "/employee/workspace", icon: "workspace" },
      { label: "Assigned Tasks", href: "/employee/assigned-tasks", icon: "tasks" },
      { label: "Available Tasks", href: "/employee/available-tasks", icon: "tasks" },
      { label: "Requests", href: "/employee/requests", icon: "inbox" },
      { label: "Clock In", href: "/employee/clock-in", icon: "calendar" },
      { label: "Clock Out", href: "/employee/clock-out", icon: "calendar" },
      { label: "Team", href: "/employee/team", icon: "users" },
      { label: "Inbox", href: "/employee/inbox", icon: "inbox" },
      { label: "My Space", href: "/employee/my-space", icon: "home" },
      { label: "Profile", href: "/employee/profile", icon: "home" },
      { label: "Support", href: "/employee/support", icon: "support" },
    ],
  },
};
