Table organization {
    organization_id uuid [pk]
    organization_name varchar [not null]
    organization_code varchar [unique]
    organization_email varchar [unique]
    organization_type varchar
    logo_url text
    created_at timestamptz [not null, default: `now()`]
    updated_at timestamptz
}

Table role {
    role_id int [pk]
    role_name varchar [not null, unique]
    description text
    created_at timestamptz [not null, default: `now()`]
    updated_at timestamptz
}

Table user_account {
    user_id uuid [pk]
    role_id int [ref: > role.role_id]
    organization_id uuid [ref: > organization.organization_id]
    username varchar [not null, unique]
    email varchar [not null, unique]
    account_status varchar [not null, default: 'Active']
    created_at timestamptz [not null, default: `now()`]
    updated_at timestamptz
}

Table profile {
    profile_id uuid [pk]
    user_id uuid [unique, ref: > user_account.user_id]
    full_name varchar
    phone_number varchar
    address text
    bio text
    profile_picture_url text
    created_at timestamptz [not null, default: `now()`]
    updated_at timestamptz
}



Table availability {
    availability_id int [pk]
    user_id uuid [ref: > user_account.user_id]
    day_of_week varchar
    start_time time
    end_time time
    status varchar
}

Table skill {
    skill_id int [pk]
    skill_name varchar unique
    description text
    created_at timestamptz
    updated_at timestamptz
}

Table user_skill {
    user_id uuid [ref: > user_account.user_id]
    skill_id int [ref: > skill.skill_id]
    proficiency_level int
    created_at timestamptz
    updated_at timestamptz
}

Table qualification {
    qualification_id int [pk]
    qualification_name varchar unique
    description text
    created_at timestamptz
    updated_at timestamptz
}

Table user_qualification {
    user_id uuid [ref: > user_account.user_id]
    qualification_id int [ref: > qualification.qualification_id]
    institution varchar
    graduation_year int
    created_at timestamptz
    updated_at timestamptz
}



Table task {
    task_id int [pk]
    organization_id uuid [ref: > organization.organization_id]
    task_code varchar
    title varchar
    description text
    status varchar
    start_datetime timestamptz
    end_datetime timestamptz
    created_at timestamptz
    updated_at timestamptz
    "organization_id, task_code" unique
}

Table task_skill {
    task_id int [ref: > task.task_id]
    skill_id int [ref: > skill.skill_id]
    created_at timestamptz
    updated_at timestamptz
}

Table task_qualification {
    task_id int [ref: > task.task_id]
    qualification_id int [ref: > qualification.qualification_id]
    created_at timestamptz
    updated_at timestamptz
}

Table task_assignment {
    assignment_id int [pk]
    task_id int [ref: > task.task_id]
    user_id uuid [ref: > user_account.user_id]
    assigned_at timestamptz
    status varchar
}

Table task_assignment_request {
    request_id int [pk]
    task_id int [ref: > task.task_id]
    user_id uuid [ref: > user_account.user_id]
    requested_at timestamptz
    status varchar
}

Table notification {
    notification_id int [pk]
    user_id uuid [ref: > user_account.user_id]
    message text
    is_read boolean
    created_at timestamptz
}

Table activity_log {
    log_id int [pk]
    user_id uuid [ref: > user_account.user_id]
    action varchar
    details text
    created_at timestamptz
}
